Update pretrain_IJEPA.py
Add the m_start_end parms as an attribute for the class IJEPA, because it's producing an error while training:
"""AttributeError: 'IJEPA' object has no attribute 'm_start_end'"""